### ISSUE TITLE
useLayoutEffect warning

### ISSUE THREAD

**Issue by csoylu** [kamp-us/monorepo#195]
### Describe the bug

Each time a Comment item is rendered, we get this warning.
```js
pano-app-1       | @kampus-apps/pano:docker: Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
pano-app-1       | @kampus-apps/pano:docker:     at CommentItem (/app/apps/pano/build/index.js:1255:3)
pano-app-1       | @kampus-apps/pano:docker:     at div
pano-app-1       | @kampus-apps/pano:docker:     at div
pano-app-1       | @kampus-apps/pano:docker:     at Styled.div
pano-app-1       | @kampus-apps/pano:docker:     at div
pano-app-1       | @kampus-apps/pano:docker:     at Styled.div
pano-app-1       | @kampus-apps/pano:docker:     at CommentItem (/app/apps/pano/build/index.js:1255:3)
pano-app-1       | @kampus-apps/pano:docker:     at div
pano-app-1       | @kampus-apps/pano:docker:     at div
pano-app-1       | @kampus-apps/pano:docker:     at Styled.div
pano-app-1       | @kampus-apps/pano:docker:     at div
pano-app-1       | @kampus-apps/pano:docker:     at Styled.div
pano-app-1       | @kampus-apps/pano:docker:     at CommentItem (/app/apps/pano/build/index.js:1255:3)
pano-app-1       | @kampus-apps/pano:docker:     at div
pano-app-1       | @kampus-apps/pano:docker:     at Styled.div
pano-app-1       | @kampus-apps/pano:docker:     at SinglePost (/app/apps/pano/build/index.js:2278:14)
pano-app-1       | @kampus-apps/pano:docker:     at RemixRoute (/app/node_modules/@remix-run/react/dist/components.js:195:3)
pano-app-1       | @kampus-apps/pano:docker:     at Outlet (/app/node_modules/@remix-run/react/node_modules/react-router/umd/react-router.development.js:798:28)
pano-app-1       | @kampus-apps/pano:docker:     at UserContextManager (/app/apps/pano/build/index.js:66:3)
pano-app-1       | @kampus-apps/pano:docker:     at body
pano-app-1       | @kampus-apps/pano:docker:     at html
pano-app-1       | @kampus-apps/pano:docker:     at Document (/app/apps/pano/build/index.js:520:19)
pano-app-1       | @kampus-apps/pano:docker:     at Provider (/app/node_modules/@radix-ui/react-context/dist/index.js:47:28)
pano-app-1       | @kampus-apps/pano:docker:     at Provider (/app/node_modules/@radix-ui/react-context/dist/index.js:47:28)
pano-app-1       | @kampus-apps/pano:docker:     at CollectionProvider (/app/node_modules/@radix-ui/react-collection/dist/index.js:34:24)
pano-app-1       | @kampus-apps/pano:docker:     at $9208a85b3e79d33f$export$f5d03d415824e0e (/app/node_modules/@radix-ui/react-toast/dist/index.js:63:27)
pano-app-1       | @kampus-apps/pano:docker:     at ThemeProvider (/app/packages/kampus-ui/dist/index.js:2012:24)
pano-app-1       | @kampus-apps/pano:docker:     at App (/app/apps/pano/build/index.js:688:50)
pano-app-1       | @kampus-apps/pano:docker:     at RemixRoute (/app/node_modules/@remix-run/react/dist/components.js:195:3)
pano-app-1       | @kampus-apps/pano:docker:     at Routes (/app/node_modules/@remix-run/react/dist/components.js:172:7)
pano-app-1       | @kampus-apps/pano:docker:     at Router (/app/node_modules/@remix-run/react/node_modules/react-router/umd/react-router.development.js:821:17)
pano-app-1       | @kampus-apps/pano:docker:     at RemixCatchBoundary (/app/node_modules/@remix-run/react/dist/errorBoundaries.js:127:10)
pano-app-1       | @kampus-apps/pano:docker:     at RemixErrorBoundary (/app/node_modules/@remix-run/react/dist/errorBoundaries.js:24:5)
pano-app-1       | @kampus-apps/pano:docker:     at RemixEntry (/app/node_modules/@remix-run/react/dist/components.js:56:12)
pano-app-1       | @kampus-apps/pano:docker:     at RemixServer (/app/node_modules/@remix-run/react/dist/server.js:47:3)
```

### Steps to reproduce the behavior

Navigate to a post.

### Expected behavior

Not getting a warning that hides logs.

**Comment by csoylu** [comment]
I and @Luuwa checked and changing it with `useEffect` doesn't seem to break anything.
